### ISSUE TITLE
Log window always opening at startup

### ISSUE THREAD

**Issue by djbe** [arranger1044/iSoul#1]
The log window always opens at startup.
It seems to ignore the show log at startup preference.

**Comment by arranger1044** [comment]
Good bug spotting david. I was checking the preference in the wrong way in the code. It should be fixed now (I hope). We need a stricter (and faster) way to test things and corrections

**Comment by djbe** [comment]
GUI testing is really really hard.
(that's what users are for :-P j/k)

**Comment by arranger1044** [comment]
Shall we put a secondary branch with untested (by long use) code?
(I'm putting the commit on master, at the moment)

**Comment by djbe** [comment]
Dunno, this (trunk) is where we work on, with untested stuff and such. Whenever we feel like we can/should release something, we can just create a tag for it (and put the binary in there, they shouldn't be in trunk repo imo).

And yeah, I know trunk is from svn :-P

**Comment by arranger1044** [comment]
ok I'll follow you (my inexperience will make me say something ridiculous sometimes)

**Comment by djbe** [comment]
Well, with svn, in trunk you put the current working code. Usually (and hopefully) it works, but can and will be unstable.
Once you start approaching a milestone, you make branch for it, work on it (and merge any fixes from that branch back to trunk) until it's ready and tag it.

Right now, our "trunk" is stable I think, as we didn't modify too much of the basic code we got from the google version of the project except adding a bunch of stuff. Sure that added stuff might not be perfect, but that's what the main branch is for.

Now let's close this issue again and take this discussion if needed elsewhere :-P
