### ISSUE TITLE
isoul won't connect to soulseek

### ISSUE THREAD

**Issue by jennsucks** [arranger1044/iSoul#10]
iSoul opens and nothing happens. wrong port maybe?

**Comment by djbe** [comment]
Could you check your firewall settings and make sure that your router is correctly forwarding the necessary ports?

**Comment by jennsucks** [comment]
How do I get the router to forward to the port?

On Mon, Jan 2, 2012 at 4:17 AM, David Jennes <
reply@reply.github.com

**Comment by djbe** [comment]
http://portforward.com/

**Comment by arranger1044** [comment]
Shall we put a page on the wiki about connection issues, David?

**Comment by djbe** [comment]
Might be a good idea, some sort of FAQ maybe?

**Comment by arranger1044** [comment]
That would be good too. Is there a way to ask "our community" to lend a hand? : D

**Comment by djbe** [comment]
Is there a newsgroup, mailing list or something similar?

**Comment by arranger1044** [comment]
I guess the answer is negative

**Comment by djbe** [comment]
Well they can always use this issue tracker, or we can create a [google group](http://groups.google.com)?

Edit: I'll create one called isoul-support

**Comment by arranger1044** [comment]
Maybe at this moment we shall stick with this issue tracker

**Comment by djbe** [comment]
It wouldn't hurt you know :-D The more ways they can communicate, the better

**Comment by arranger1044** [comment]
Ok, could you get a google group running, David?

**Comment by arranger1044** [comment]
This is the url to the group David created http://groups.google.com/group/isoul-support?hl=en
