### ISSUE TITLE
Incomplete chat room list

### ISSUE THREAD

**Issue by arranger1044** [arranger1044/iSoul#11]
When I connect to the soulseek network with SoulseeX you have the option to "Reload" the chat room list and when you do it the total number of available chats largely increases. With iSoul we can only, at the moment, get the initial chat list. I guess it is the soulseek protocol that limits the initial amount of chat rooms at the first request. We shall dig deep into it.

**Comment by arranger1044** [comment]
I confirm that you need to ask the soulseek net the chat room list another time in order to get the full list. I added a button in the chat room list window toolbar to perform this task.

**Comment by djbe** [comment]
You could automate this, maybe as a delayed call 10 seconds after we first connect (or reconnect) to the network. But leave the button for users who want to do that afterwards.

**Comment by arranger1044** [comment]
I guess that it would be pointless: if I got it right the soulseek protocol does that only the first time in order to limit the number of chat rooms found (the greatest part contains only one user). Either we do this always automatically at start up (with no delay) or we leave it by user choice (with a button).
