### ISSUE TITLE
iSoul not launching - all versions - lion 10.7.3

### ISSUE THREAD

**Issue by ghost** [arranger1044/iSoul#16]
i just tried isoul again to see its progress and every time i launch it, its icon keeps bouncing on the dock. if i left click on it, isoul just quits, if i wait long enough it eventually stops bouncing but right clicking on it says "app not responding". a left click still quits it. happens from 0.3.4 to the latest beta on lion 10.7.3. fixing disk permissions and rebooting doesn't fix it. did the 10.7.3 update break anything? thanks.

**Comment by djbe** [comment]
Do you see anything of interest in the console?

**Comment by ghost** [comment]
just these 2 messages...

02-03-12 5:38:06.254 AM com.apple.launchd.peruser.501: ([0x0-0x118118].com.bdp.iSoul[1457]) posix_spawn("/Users/Damazio/Downloads/Safari/iSoul/iSoul.app/Contents/MacOS/iSoul", ...): Operation not permitted

02-03-12 5:38:06.255 AM com.apple.launchd.peruser.501: ([0x0-0x118118].com.bdp.iSoul[1457]) Exited with code: 1

launching "iSoul.app/Contents/MacOS/iSoul" returns the following in the terminal:

Last login: Thu Mar  1 03:17:50 on ttys000
/Users/Damazio/Downloads/Safari/iSoul/iSoul.app/Contents/MacOS/iSoul ; exit;
badcomputer:~ Damazio$ /Users/Damazio/Downloads/Safari/iSoul/iSoul.app/Contents/MacOS/iSoul ; exit;
-bash: /Users/Damazio/Downloads/Safari/iSoul/iSoul.app/Contents/MacOS/iSoul: Operation not permitted
logout

[Process completed]

**Comment by djbe** [comment]
try this in terminal:

```
chmod a+x ~/Downloads/Safari/iSoul/iSoul.app/Contents/MacOS/iSoul
```

**Comment by ghost** [comment]
thanks a lot, the permissions were right but i found the problem. there's a quarantine bug in lion which set isoul executable to be quarantined (there are other examples in the link below). now, i've disabled quarantine some time ago (see option 3 in the link below) but for some reason, isoul was on the list. enabling quarantine system wide (defaults write com.apple.LaunchServices LSQuarantine -bool YES) or on a file basis (xattr -d com.apple.quarantine isoul.app) solves the issue.

http://reviews.cnet.com/8301-13727_7-57374676-263/workarounds-for-quarantine-bug-in-os-x-lion/

**Comment by djbe** [comment]
Never encountered that particular bug, but I'm glad you were able to solve your issue.
