### ISSUE TITLE
some suggestions for chat/PM

### ISSUE THREAD

**Issue by jeanravin** [arranger1044/iSoul#18]
1. I really miss not having dates for messages. I often don't know if the message have been posted seconds ago or an hour ago. And it's abit frustrating.
2. I'd love to have a bouncing icon (or even growl notification) only for Personnal Messages.

**Comment by djbe** [comment]
I can try taking a look at the Growl stuff.

**Comment by arranger1044** [comment]
I added the timestamp for each message.
Concerning notifications, @djbe , a personalized system like Adium shall be the non plus ultra, but maybe too complex for just the two of us. @jeanravin we will definitely get some rationalized work done on this.
@djbe Can we put up in github a nightly builds sort of system to let some users get a compiled version with fixes?
