### ISSUE TITLE
Add Sparkle support for updates

### ISSUE THREAD

**Issue by SteveBell** [arranger1044/iSoul#22]
currently there's no good way to update an existing version from what I can tell

**Comment by arranger1044** [comment]
You are right and we talked about this in the past. @djbe have you tried to take a look at the sparkle framework

**Comment by djbe** [comment]
Working on it right now. As we don't have a web server + domain, I'm trying to host everything on Github, hopefully it'll work.

**Comment by djbe** [comment]
Fixed in af60aab89045f647b3d91d717b295e3df5e2a0e3

**Comment by SteveBell** [comment]
Great stuff :)

FYI: This is what I see when I click "Check for Updates"
http://cl.ly/0A301q0w3r2e2q0B2R1o

**Comment by arranger1044** [comment]
Maybe an attached image is missing @SteveBell

**Comment by SteveBell** [comment]
Y, added that right away. Missing in your notification though, it seems.

Tried with version from http://www.macupdate.com/find/mac/isoul and results remain the same.

**Comment by arranger1044** [comment]
I bet is the same as issue #24 https://github.com/arranger1044/iSoul/issues/24 David fixed it

**Comment by djbe** [comment]
> Missing in your notification though, it seems.

What?

**Comment by SteveBell** [comment]
@djbe Meaning that I forgot the screenshot. Then edited the post and added the screenshot. Which means arranger1044 did not receive the screenshot in his GitHub-notification (if he uses those).
