### ISSUE TITLE
Bug/feature: resume uploads

### ISSUE THREAD

**Issue by artelse** [arranger1044/iSoul#29]
Bug: When one tries to resume a stalled or "cannot connect" upload, the queued file is transferred to the download queue.. After that it disrupts the queue; i.e. one cannot delete an item in the queue any longer, it just reappears.

Feature: To resolve that problem, allow resuming of stalled uploads.

**Comment by arranger1044** [comment]
You're right, in the legacy code a resumed upload was treated as a new download (dunno why). I hope I fixed it now, I'm closing this  issue but feel free to reopen it after testing.
