### ISSUE TITLE
some characters are not supported

### ISSUE THREAD

**Issue by jeanravin** [arranger1044/iSoul#35]
Some special characters (like this one: ’) or some languages glyphs (like japanese) are not supported. When browsing my own files these characters are replaced with "ï¿½ï¿½ï¿½" chains. The problematic thing is I can't upload these files. I see errors of files being not present (don't remember the exact error name right now).

**Comment by naos** [comment]
This is soulseek network character encoding problem.
You can solve this issue by changing values in the **~/Library/Application Support/iSoul/0.3/config.xml**

change from

``` xml
<domain id="encoding">
    <key id="filesystem">UTF-8-MAC</key>
    <key id="network">ISO-8859-1</key>
</domain>
```

to

``` xml
<domain id="encoding">
    <key id="filesystem">UTF-8-MAC</key>
    <key id="network">UTF-8-MAC</key>
</domain>
```

Then you will be able to see filenames of your own files correctly.
Before you change the value you need to be sure that iSoul (more precisely museekd) is not running.

This won't solve some other issues such as problem with downloading and uploading files with filenames that contain such characters.

Character encoding for network is set to a value of "ISO-8859-1" for a reason. Currently the majority of clients on the soulseek network are using soulseek version 157 which uses default encoding for specific windows localization (in the case of english and western european localizations that is ISO-8859-1, japanese version is using SHIFT-JIS, korean EUC-KR etc.). There are lots of these encodings and they are not compatible with each other (although the basic latin set - first 128 characters in ASCII encoding is usually supported in all the encodings). Unicode encodings, such as UTF8, are currently the best choice for supporting multilingual environments.

If you make this change, and the user from whom you are downloading (or who is downloading from you) is using soulseek client that natively supports UTF8 encoding (such as soulseekqt) everything will work smoothly. In all other cases it will be problematic to download/upload files with filenames that contain characters from extended character set.
If the character encoding for network is set to "ISO-8859-1" at least you will be able to download from majority of users without the problem (although the filenames won't be displayed correctly in some cases).

**Comment by djbe** [comment]
That's some good info there, @naos. Closing this for now.

**Comment by jeanravin** [comment]
Indeed. Thanks for your explanation.
