### ISSUE TITLE
Growl notifications for downloads alert when the transfer is an upload too

### ISSUE THREAD

**Issue by arranger1044** [arranger1044/iSoul#5]
The Growl notification system appears not to make difference between finished uploads and downloads always saying it's a download.
I remember that the difference from downloads and uploads in the original iSoul was not handled properly.

**Comment by djbe** [comment]
Huh, can't say I tested that since I never had any uploads :-P

This one might be harder to do if iSoul itself doesn't handle the difference internally...

**Comment by arranger1044** [comment]
The difference is held somewhere internally, you can just check it from a transfer in the DB, the problem is that is not a 'clean' solution (if I remember correctly).

**Comment by djbe** [comment]
Heh, whatever works :-P
